export const DAFTAR_INSTANSI_PD = [
  "Dinas Kesehatan",
  "Dinas Pendidikan",
  "Dinas Pekerjaan Umum dan Penataan Ruang",
  "Dinas Sosial",
  "Dinas Tenaga Kerja",
  "Dinas Lingkungan Hidup",
  "Dinas Perhubungan",
  "Dinas Komunikasi dan Informatika",
  "Dinas Koperasi dan UKM",
  "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
  "Badan Perencanaan Pembangunan Daerah",
  "Badan Pendapatan Daerah",
  "Badan Kepegawaian Daerah",
  "Dinas Pemberdayaan Masyarakat dan Desa",
  "Dinas Pemuda dan Olahraga",
  "Dinas Pariwisata",
  "Dinas Pertanian",
  "Dinas Ketahanan Pangan",
  "Dinas Perindustrian dan Perdagangan",
  "Dinas Perumahan dan Kawasan Permukiman",
  "Satuan Polisi Pamong Praja",
  "Badan Penanggulangan Bencana Daerah",
  "Badan Kesatuan Bangsa dan Politik",
  "Inspektorat Daerah",
  "Rumah Sakit Umum Daerah"
];

export const KATEGORI_USULAN = [
  "Infrastruktur",
  "Kesehatan",
  "Pendidikan",
  "Ekonomi",
  "Sosial",
  "Lingkungan",
  "Lainnya"
];

export const DAFTAR_KAB_KOTA = [
  "Kabupaten Asahan",
  "Kabupaten Batubara",
  "Kabupaten Dairi",
  "Kabupaten Deli Serdang",
  "Kabupaten Humbang Hasundutan",
  "Kabupaten Karo",
  "Kabupaten Labuhanbatu",
  "Kabupaten Labuhanbatu Selatan",
  "Kabupaten Labuhanbatu Utara",
  "Kabupaten Langkat",
  "Kabupaten Mandailing Natal",
  "Kabupaten Nias",
  "Kabupaten Nias Barat",
  "Kabupaten Nias Selatan",
  "Kabupaten Nias Utara",
  "Kabupaten Padang Lawas",
  "Kabupaten Padang Lawas Utara",
  "Kabupaten Pakpak Bharat",
  "Kabupaten Samosir",
  "Kabupaten Serdang Bedagai",
  "Kabupaten Simalungun",
  "Kabupaten Tapanuli Selatan",
  "Kabupaten Tapanuli Tengah",
  "Kabupaten Tapanuli Utara",
  "Kabupaten Toba",
  "Kota Binjai",
  "Kota Gunungsitoli",
  "Kota Medan",
  "Kota Padangsidimpuan",
  "Kota Pematangsiantar",
  "Kota Sibolga",
  "Kota Tanjungbalai",
  "Kota Tebing Tinggi"
];
